site_title = "MyArxiv"
limit_days = 7
cache_url = "https://davidingplus.github.io/my-arxiv/cache.json"

# see more on: https://arxiv.org/category_taxonomy

[[sources]]
limit = 150
category = "cs.OS"
title = "Operating Systems"

[[sources]]
limit = 150
category = "cs.SY"
title = "Systems and Control"

[[sources]]
limit = 150
category = "cs.AR"
title = "Hardware Architecture"

[[sources]]
limit = 150
category = "cs.PL"
title = "Programming Languages"

[[sources]]
limit = 150
category = "cs.DS"
title = "Data Structures and Algorithms"

[[sources]]
limit = 150
category = "cs.GR"
title = "Graphics"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
