name: Update

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download ArxivFeed
        env:
          GITHUB_PAT: ${{ github.token }}
          REPO: "NotCraft/ArxivFeed"
          VERSION: "latest"
          MATCH: "arxivfeed-.+-x86_64-unknown-linux-musl.tar.gz$"
          RENAME: "arxivfeed.tgz"
        shell: bash
        run: |
          curl -sL --fail \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${GITHUB_PAT}" \
              "https://api.github.com/repos/${REPO}/releases/${VERSION}" \
              | jq -r ".assets | .[] | select(.name | test(\"${MATCH}\")) | .url" \
              | tee asset.url
          curl -sL --fail \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${GITHUB_PAT}" \
              -o "${RENAME}" \
              "$(cat asset.url)"
          tar -zxvf arxivfeed.tgz --strip-components 1 $(tar tf arxivfeed.tgz | grep /arxivfeed)
          chmod +x arxivfeed
      - name: Build rss
        run: ./arxivfeed
      - name: Copy Azure SWA workflow to target
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          mkdir -p ${WORKSPACE}/target/
          mkdir -p ${WORKSPACE}/target/.github/workflows/
          cp ${WORKSPACE}/.github/workflows/azure-static-web-apps-lemon-glacier-047586300.yml ${WORKSPACE}/target/.github/workflows/
      - uses: actions/upload-artifact@v4
        with:
          name: target
          path: target
          include-hidden-files: true
          if-no-files-found: error

  deploy-to-gh-pages-deprecated:
    name: Deploy to gh-pages-deprecated
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: target
          path: target
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages-deprecated
          build_dir: target
          keep_history: false
          allow_empty_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 

  deploy-to-deno:
    name: Deploy to Deno
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: target
          path: target
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: my-arxiv-davidingplus
          entrypoint: https://deno.land/std/http/file_server.ts
          root: ./target
